### ISSUE TITLE
zooming floormap results in app crash

### ISSUE THREAD

**Issue by atsushieno** [DroidKaigi/conference-app-2019#531] opened 2019-01-18 18:07 UTC
**zooming floormap results in crash**

**Steps To Reproduce**

1. Go to floormap via the hamburger menu
2. pinch the map to zoom in. You most likely need the latest-ish app after https://github.com/DroidKaigi/conference-app-2019/pull/517

It does not always crash, it is sort of conditional. Probably the crash log below gives some hints on how to exactly reproduce it.

**Expected behavior**

The app should not crash.

**Screenshots**
**Env:**

See the crash log appended below.

**Additional context**

crash log:

```
Application: io.github.droidkaigi.confsched2019.debug
Manufacturer: Google
Model: Pixel 2
Brand: google
Device: walleye
Board: walleye
Hardware: walleye
Product: walleye
Android Version: 9


java.lang.IllegalArgumentException: pointerIndex out of range
   android.view.MotionEvent.nativeGetAxisValue(Native Method)
   android.view.MotionEvent.getX(MotionEvent.java:2205)
   androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
   android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
   com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
   com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
   android.app.Activity.dispatchTouchEvent(Activity.java:3400)
   androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
   androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
   com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
   android.view.View.dispatchPointerEvent(View.java:12752)
   android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
   android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
   android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
   android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
   android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
   android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
   android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
   android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
   android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
   android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
   android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
   android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
   android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
   android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
   android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
   android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
   android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
   android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
   android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
   android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
   android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7166)
   android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7218)
   android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
   android.view.Choreographer.doCallbacks(Choreographer.java:761)
   android.view.Choreographer.doFrame(Choreographer.java:690)
   android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
   android.os.Handler.handleCallback(Handler.java:873)
   android.os.Handler.dispatchMessage(Handler.java:99)
   android.os.Looper.loop(Looper.java:193)
   android.app.ActivityThread.main(ActivityThread.java:6718)
   java.lang.reflect.Method.invoke(Native Method)
   com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
   com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by takahirom** [comment] 2019-01-18 18:08
Thanks! probably dupe of https://github.com/DroidKaigi/conference-app-2019/issues/523

**Closed** 2019-01-18 18:08 UTC
Labels: bug
