### ISSUE TITLE
Fix session list is not displayed

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#157] opened 2019-01-05 16:31 UTC
## Overview (Required)
- I don't know how to reproduce.

![screenshot_20190105-184656](https://user-images.githubusercontent.com/5106629/50726581-b7ca7500-1152-11e9-8eec-3aa6a56026dc.png)

## Links
-

**Comment by kafumi** [comment] 2019-01-10 18:00
I've figured out the root cause. Let me propose a possible fix later.

**Comment by jmatsu** [comment] 2019-01-10 18:03
Lovely! Let us assign this issue to you for now. 🥇

**Closed** 2019-01-11 01:57 UTC
Labels: assigned, help wanted, high priority, welcome contribute
